In [1]:
mat1 <- matrix(data=c(1,2,3,4))
mat1

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4

In [2]:
mat2 <- matrix(data=c(1,2,3,4),nrow=2,ncol=2)
mat2

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [7]:
mat3 <- matrix(data=c(1,2,3,4),nrow=2,ncol=2,byrow=T)
mat3
dim(mat3)
mat3[1,2]
mat3[1,]
mat3[,1]

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[1] 2 2

[1] 2

[1] 1 2

[1] 1 3

In [13]:
mat4 <- rbind(1:3,4:6,7:9)
mat4
mat4[2:3,]
mat4[-2,]
mat4[1,1]<-0
mat4
mat4[1,]<- c(10,11,12)
mat4

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 4    5    6   
[2,] 7    8    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 7    8    9

[,1] [,2] [,3]
[1,] 0    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 10   11   12  
[2,]  4    5    6  
[3,]  7    8    9